class ProductsErrorCode:
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    SLUG_ALREADY_EXISTS = "SLUG_ALREADY_EXISTS"
    TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
    VARIANT_NOT_FOUND = "VARIANT_NOT_FOUND"
