"""initial_schema

Revision ID: 19ff66ea5b1f
Revises:
Create Date: 2026-06-28 03:08:26.264325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19ff66ea5b1f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_email_idx"), table_name="user")
    op.drop_table("user")
    op.add_column("admin_user", sa.Column("first_name", sa.String(length=128), nullable=False))
    op.add_column("admin_user", sa.Column("last_name", sa.String(length=128), nullable=False))
    op.add_column("admin_user", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.add_column("admin_user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("admin_user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_user", sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False)
    )
    op.drop_column("admin_user", "is_active")
    op.drop_column("admin_user", "is_admin")
    op.drop_column("admin_user", "last_name")
    op.drop_column("admin_user", "first_name")
    op.create_table(
        "user",
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("user_email_idx"), "user", ["email"], unique=True)
    # ### end Alembic commands ###
