"""initial_schema

Revision ID: e2a52e622f6b
Revises:
Create Date: 2026-07-03 01:15:09.306861

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a52e622f6b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_display_id_seq START 1000")
    op.execute("CREATE SEQUENCE IF NOT EXISTS doc_display_id_seq START 1000")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_template",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("attribute_template_pkey")),
        sa.UniqueConstraint("name", name=op.f("attribute_template_name_key")),
    )
    op.create_table(
        "category",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
            name=op.f("category_parent_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("category_pkey")),
    )
    op.create_index(op.f("category_parent_id_idx"), "category", ["parent_id"], unique=False)
    op.create_index(op.f("category_slug_idx"), "category", ["slug"], unique=True)
    op.create_table(
        "customer",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("customer_pkey")),
    )
    op.create_index(op.f("customer_email_idx"), "customer", ["email"], unique=True)
    op.create_table(
        "image",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["image.id"], name=op.f("image_parent_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("image_pkey")),
    )
    op.create_index(op.f("image_entity_id_idx"), "image", ["entity_id"], unique=False)
    op.create_index(op.f("image_entity_type_idx"), "image", ["entity_type"], unique=False)
    op.create_table(
        "shipping_zone",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("countries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("shipping_zone_pkey")),
    )
    op.create_table(
        "store_setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("store_setting_pkey")),
        sa.UniqueConstraint("key", name=op.f("store_setting_key_key")),
    )
    op.create_index(op.f("store_setting_key_idx"), "store_setting", ["key"], unique=False)
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("user_email_idx"), "user", ["email"], unique=True)
    op.create_table(
        "address",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("address_line1", sa.String(length=256), nullable=False),
        sa.Column("address_line2", sa.String(length=256), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("postal_code", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("address_customer_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("address_pkey")),
    )
    op.create_index(op.f("address_customer_id_idx"), "address", ["customer_id"], unique=False)
    op.create_table(
        "cart",
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customer.id"], name=op.f("cart_customer_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cart_pkey")),
    )
    op.create_index(op.f("cart_customer_id_idx"), "cart", ["customer_id"], unique=True)
    op.create_index(op.f("cart_session_id_idx"), "cart", ["session_id"], unique=False)
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("attribute_template_id", sa.UUID(), nullable=True),
        sa.Column(
            "variant_attributes_override", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_template_id"],
            ["attribute_template.id"],
            name=op.f("product_attribute_template_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("product_category_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_pkey")),
    )
    op.create_index(op.f("product_category_id_idx"), "product", ["category_id"], unique=False)
    op.create_index(op.f("product_slug_idx"), "product", ["slug"], unique=True)
    op.create_table(
        "shipping_rate",
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_cost", sa.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column("free_above", sa.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("max_weight_kg", sa.DECIMAL(precision=8, scale=3), nullable=True),
        sa.Column("min_subtotal", sa.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("min_days", sa.Integer(), nullable=True),
        sa.Column("max_days", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["shipping_zone.id"],
            name=op.f("shipping_rate_zone_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("shipping_rate_pkey")),
    )
    op.create_index(op.f("shipping_rate_zone_id_idx"), "shipping_rate", ["zone_id"], unique=False)
    op.create_table(
        "order",
        sa.Column(
            "display_id",
            sa.Integer(),
            server_default=sa.text("nextval('order_display_id_seq')"),
            nullable=False,
        ),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("exchange_rate", sa.DECIMAL(precision=14, scale=8), nullable=True),
        sa.Column("total_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("subtotal", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column("base_total_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("base_subtotal", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("base_tax_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("base_shipping_cost", sa.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("shipping_address_id", sa.UUID(), nullable=True),
        sa.Column("shipping_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("shipping_rate_id", sa.UUID(), nullable=True),
        sa.Column("estimated_delivery", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("order_customer_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"],
            ["address.id"],
            name=op.f("order_shipping_address_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shipping_rate_id"],
            ["shipping_rate.id"],
            name=op.f("order_shipping_rate_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_pkey")),
    )
    op.create_index(op.f("order_customer_id_idx"), "order", ["customer_id"], unique=False)
    op.create_index(op.f("order_display_id_idx"), "order", ["display_id"], unique=True)
    op.create_table(
        "product_variant",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("price_override", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.DECIMAL(precision=8, scale=3), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("product_variant_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_variant_pkey")),
        sa.UniqueConstraint("sku", name=op.f("product_variant_sku_key")),
    )
    op.create_index(
        op.f("product_variant_product_id_idx"), "product_variant", ["product_id"], unique=False
    )
    op.create_table(
        "cart_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["cart.id"], name=op.f("cart_item_cart_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("cart_item_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variant.id"],
            name=op.f("cart_item_variant_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cart_item_pkey")),
        sa.UniqueConstraint(
            "cart_id", "product_id", "variant_id", name="cart_item_cart_product_variant_key"
        ),
    )
    op.create_table(
        "document",
        sa.Column(
            "display_id",
            sa.Integer(),
            server_default=sa.text("nextval('doc_display_id_seq')"),
            nullable=False,
        ),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subtotal", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("document_customer_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("document_order_id_fkey"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_pkey")),
        sa.UniqueConstraint("display_id", name=op.f("document_display_id_key")),
    )
    op.create_index(op.f("document_customer_id_idx"), "document", ["customer_id"], unique=False)
    op.create_index(op.f("document_order_id_idx"), "document", ["order_id"], unique=False)
    op.create_table(
        "order_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column("variant_sku", sa.String(length=128), nullable=True),
        sa.Column("product_name", sa.String(length=256), nullable=False),
        sa.Column("product_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("product_image_url", sa.String(length=2048), nullable=True),
        sa.Column("line_total", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("order_item_order_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("order_item_product_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variant.id"],
            name=op.f("order_item_variant_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_item_pkey")),
    )
    op.create_table(
        "payment",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=256), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("payment_order_id_fkey"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("payment_pkey")),
    )
    op.create_index(op.f("payment_order_id_idx"), "payment", ["order_id"], unique=False)
    op.create_table(
        "document_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=256), nullable=False),
        sa.Column("product_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("product_image_url", sa.String(length=2048), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_total", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("document_item_document_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_item_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_item")
    op.drop_index(op.f("payment_order_id_idx"), table_name="payment")
    op.drop_table("payment")
    op.drop_table("order_item")
    op.drop_index(op.f("document_order_id_idx"), table_name="document")
    op.drop_index(op.f("document_customer_id_idx"), table_name="document")
    op.drop_table("document")
    op.drop_table("cart_item")
    op.drop_index(op.f("product_variant_product_id_idx"), table_name="product_variant")
    op.drop_table("product_variant")
    op.drop_index(op.f("order_display_id_idx"), table_name="order")
    op.drop_index(op.f("order_customer_id_idx"), table_name="order")
    op.drop_table("order")
    op.drop_index(op.f("shipping_rate_zone_id_idx"), table_name="shipping_rate")
    op.drop_table("shipping_rate")
    op.drop_index(op.f("product_slug_idx"), table_name="product")
    op.drop_index(op.f("product_category_id_idx"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("cart_session_id_idx"), table_name="cart")
    op.drop_index(op.f("cart_customer_id_idx"), table_name="cart")
    op.drop_table("cart")
    op.drop_index(op.f("address_customer_id_idx"), table_name="address")
    op.drop_table("address")
    op.drop_index(op.f("user_email_idx"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("store_setting_key_idx"), table_name="store_setting")
    op.drop_table("store_setting")
    op.drop_table("shipping_zone")
    op.drop_index(op.f("image_entity_type_idx"), table_name="image")
    op.drop_index(op.f("image_entity_id_idx"), table_name="image")
    op.drop_table("image")
    op.drop_index(op.f("customer_email_idx"), table_name="customer")
    op.drop_table("customer")
    op.drop_index(op.f("category_slug_idx"), table_name="category")
    op.drop_index(op.f("category_parent_id_idx"), table_name="category")
    op.drop_table("category")
    op.drop_table("attribute_template")
    op.execute("DROP SEQUENCE IF EXISTS doc_display_id_seq")
    op.execute("DROP SEQUENCE IF EXISTS order_display_id_seq")
    # ### end Alembic commands ###
